# Site settings
title: Your awesome title
email: anele@acedesigns.co.za
description: > # this means to ignore newlines until "baseurl:"
  A young and talented guy from Cape Town with a deep passion for design and everything web is always up for a challenge
    to develop and create something extraordinary.
    My greatest challenge yet is learning JAVA and creating just a small Android APP..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "acedesigns.co.za" # the base hostname & protocol for your site
twitter_username: anele_ace
github_username:  acedesigns

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: anele@acedesigns.co.za
  facebook:
  flickr:
  github: acedesigns
  instagram:
  linkedin: anele
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: anele_ace
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Build settings
markdown: kramdown

# Serving
detach:  false
port:    1880
host:    127.0.0.1
#baseurl: "" # does not include hostname
